[package]
name = "ai-client"
version = "0.1.0"
description = "A client to use AI tools"
authors = ["robertpakalns"]
edition = "2024"

[build-dependencies]
tauri-build = { version = "2.5.1", features = [] }

[dependencies]
tauri = { version = "2.9.2", features = [] }
